### ISSUE TITLE
Add BO3 and map veto in the future?

### ISSUE THREAD

**Issue by killer2gudpl** [playliga/application#274]
## Is your feature request related to a problem? Please describe.

Nope.

## Describe the solution you'd like

BO3 could be used in case of any tournaments, quaterfinals etc. Could be returning you to home screen before new map starts to save progress.

Map vetos could be a nice thing to add as well in that particular case, maybe even for BO1s?

## Describe alternatives you've considered

N/A, just an idea for the future :)

## Additional context

N/A

**Comment by lemonpole** [comment]
Closing in favor of #248.
